### ISSUE TITLE
hi, why heu repo is empty? The whole project cannot run

### ISSUE THREAD

**Issue by peiji1981** [secretflow/heu#1]

**Comment by usafchn** [comment]
@peiji1981 Thank you for your attention, the code of HEU is expected to be uploaded on July 2nd

**Comment by peiji1981** [comment]
thx

**Comment by usafchn** [comment]
hi, @peiji1981 

The HEU code has been uploaded and the documentation will be released in about a week.

You can install HEU with the following command
```
pip install sf-heu
```

Or you can install the latest secretflow package, heu will be automatically installed as a dependent package
```
pip install -U secretflow
```
