### ISSUE TITLE
增加secret_key构建hekit接口

### ISSUE THREAD

**Issue by tarantula-leo** [secretflow/heu#106]
目前可从公钥构造destinationhekit，得到evaluator、encryptor，但在仅有sk场景下（实际使用中只会对sk/pk进行序列化，不会对hekit做序列化），无法构造hekit对密文进行解密；
可类似地提供如下接口：
```
setup(public_key: heu.heu.phe.SecretKey) -> heu.heu.phe.xxxHeKit
# Setup phe environment by an already generated secret key.
decryptor(self: [heu.heu.phe.xxxHeKit] → heu::lib::phe::Decryptor
# Get decryptor
```

**Comment by usafchn** [comment]
好的，我们加一个从 sk 恢复 HeKit 的接口

**Comment by tarantula-leo** [comment]
1. 增加完成是否可以提供wheel包下载/pip更新？
2. pk_buffer的接口在python中是否未开放：
```
DestinationHeKit::DestinationHeKit(std::shared_ptr<PublicKey> pk) {
  Setup(std::move(pk));
  public_key_->Visit(HE_DISPATCH(HE_SPECIAL_SETUP_BY_PK));
}

DestinationHeKit::DestinationHeKit(yacl::ByteContainerView pk_buffer) {
  auto pk = std::make_shared<PublicKey>();
  pk->Deserialize(pk_buffer);
  Setup(std::move(pk));
  public_key_->Visit(HE_DISPATCH(HE_SPECIAL_SETUP_BY_PK));
}

}  // namespace heu::lib::phe
```

**Comment by usafchn** [comment]
> 1. 增加完成是否可以提供wheel包下载/pip更新？
> 2. pk_buffer的接口在python中是否未开放：
> 


1. 会提供
2. Python 中直接 `kit = phe.setup(pickle.loads(pk_buffer))`

**Comment by usafchn** [comment]
@tarantula-leo 这个是开放给 C++ 应用的接口，如果是 Python 侧过来的请求不会用到这个接口

**Comment by usafchn** [comment]
@tarantula-leo 

Pip 包 https://pypi.org/project/sf-heu/0.5.0.dev20231128/

**Comment by tarantula-leo** [comment]
看merge的内容，是通过pk和sk恢复Hekit，如果对于Decryptor的单独使用，是不是只需要sk就可以？是否会考虑增加一个单独的HeKit类，类似DestinationHekit供Encryptor/Evaluator使用。

**Comment by tarantula-leo** [comment]
升级后，这段代码会报错，pk_str是序列化后保存成String的pk：
```
def encrypt(pk_str, target):
    pk_buffer = bytes((codecs.escape_decode(str.encode(pk_str[2:-1]), "hex-escape"))[0])
    kit = phe.setup(pickle.loads(pk_buffer))
    encryptor = kit.encryptor()
    encoder = kit.float_encoder()
    clear = encoder.encode(float(target))
    cipher = encryptor.encrypt(clear)
    return pickle.dumps(cipher)
```
报错内容：
`heu.phe.PheRuntimeError: [Enforce fail at external/yacl/yacl/math/mpint/mp_int.cc:542] (mp_invmod(&a.n_, &mod.n_, &c->n_)) == MP_OKAY. -3 vs 0`

**Comment by usafchn** [comment]
> 看merge的内容，是通过pk和sk恢复Hekit，如果对于Decryptor的单独使用，是不是只需要sk就可以？是否会考虑增加一个单独的HeKit类，类似DestinationHekit供Encryptor/Evaluator使用。

这个不考虑，有些算法的 decrypt 依赖 pk 中的内容，所以 HEU 构造 Decryptor 的时候默认需要传入 pk 和 sk，上层多传一个 pk 应该不困难吧？
