### ISSUE TITLE
heu是否有类似spu runtimeconfig的enable_action_trace开关？

### ISSUE THREAD

**Issue by mingo0117** [secretflow/heu#11]
如题，想看下tracelog学习下，看源码似乎还不支持？求教，谢谢

**Comment by usafchn** [comment]
hi, @mingo0117 感谢关注
HEU 目前还没有引入编译器层，也没有引入 IR，因此没有 trace 开关，如果你对 HEU 感兴趣的话，可以参考文档 https://heu.readthedocs.io/zh_CN/latest/getting_started/quick_start.html ，并结合 HEU 代码 （入口 https://github.com/secretflow/heu/blob/beta/heu/library/phe/phe.h ） 看下，整体不复杂

**Comment by mingo0117** [comment]
> hi, @mingo0117 感谢关注 HEU 目前还没有引入编译器层，也没有引入 IR，因此没有 trace 开关，如果你对 HEU 感兴趣的话，可以参考文档 https://heu.readthedocs.io/zh_CN/latest/getting_started/quick_start.html ，并结合 HEU 代码 （入口 https://github.com/secretflow/heu/blob/beta/heu/library/phe/phe.h ） 看下，整体不复杂

好的，感谢答复!
