### ISSUE TITLE
import heu时发生Illegal instruction(core dumped)

### ISSUE THREAD

**Issue by cnsunfocus** [secretflow/heu#113]
执行from heu import numpy as hnp 有错误 Illegal instruction (core dumped)
简单gdb了一下， 有以下信息：
Program received signal SIGILL, Illegal instruction.
0x00007f2e76959cbb in e9_ippsBigNumInit () from /usr/local/lib64/python3.8/site-packages/heu.so

版本信息：
os： centos 8.3
kernel: 4.18.0-348.el8.x86_64
python: 3.8.8
heu:   sf-heu             0.5.0.dev20231128
cpu：
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2493.988
cache size      : 16384 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 4987.97
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by anakinxc** [comment]
Hi @cnsunfocus 

HEU 需要处理器支持 AVX 指令集

**Comment by cnsunfocus** [comment]
> 需要处理器支持 AVX 指令集

嗯， 回退到0.44解决了
