### ISSUE TITLE
bazel compile error

### ISSUE THREAD

**Issue by hushanxue** [secretflow/heu#12]
heu/library/phe/phe.cc:47:45:   required from here
/usr/include/c++/9/ext/new_allocator.h:146:4: error: use of deleted function 'heu::lib::phe::PublicKey::PublicKey()'
  146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./heu/library/phe/decryptor.h:19,
                 from ./heu/library/phe/phe.h:17,
                 from heu/library/phe/phe.cc:15:
(base) root@DESKTOP-62A5JFJ:~/work/secretflow/secretflow_lib/third_party/heu# gcc -v
   83 | class PublicKey : public SerializableVariant<HE_NAMESPACE_LIST(PublicKey)> {
      |       ^~~~~~~~~
./heu/library/phe/serializable_types.h:83:7: **error: use of deleted function 'constexpr** heu::lib::phe::SerializableVariant<Types>::SerializableVariant() [with Types = {heu::lib::algorithms::mock::PublicKey, heu::lib::algorithms::paillier_z::PublicKey, heu::lib::algorithms::paillier_f::PublicKey}]'
./heu/library/phe/serializable_types.h:33:3: note: 'constexpr heu::lib::phe::SerializableVariant<Types>::SerializableVariant() noexcept [with Types = {heu::lib::algorithms::mock::PublicKey, heu::lib::algorithms::paillier_z::PublicKey, heu::lib::algorithms::paillier_f::PublicKey}]' **is implicitly deleted because its exception-specification does not match the implicit exception-specification 'noexcept (false)'**
   33 |   SerializableVariant() noexcept = default;
      |   ^~~~~~~~~~~~~~~~~~~
Target //heu/library/phe:phe failed to build
INFO: Elapsed time: 17.709s, Critical Path: 15.40s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully

**Comment by anakinxc** [comment]
请问 gcc 版本是多少？

**Comment by hushanxue** [comment]
> 请问 gcc 版本是多少？

9.4.0

**Comment by hushanxue** [comment]
> 请问 gcc 版本是多少？
gcc 需要10吗？

**Comment by anakinxc** [comment]
> 请问 gcc 版本是多少？
> gcc 需要10吗？

我们统一都使用的 gcc11

**Comment by hushanxue** [comment]
> > 请问 gcc 版本是多少？
> > gcc 需要10吗？
> 
> 我们统一都使用的 gcc11

好的，谢谢，明白了，我升级一下
