### ISSUE TITLE
...../com_alipay_sf_heu/heu/pybind/phe.so: undefined symbol: PyFrame_GetCode

### ISSUE THREAD

**Issue by hushanxue** [secretflow/heu#13]
**1、I compile heu using the below bazel command:**
------------------------------------------------------------------

bazel build --verbose_failures //heu/library/phe

bazel test //heu/library/phe:phe_test

bazel build -c opt //heu:heu_wheel
pip install bazel-bin/heu/(cat bazel-bin/heu/heu_wheel.name) --force-reinstall

bazel test //heu/pybind:phe_test

---------------------------------------------------------------------------------------------

**2、 last command [bazel test //heu/pybind:phe_test], I got an error, My python is 3.8.13:**
------------------------------------------------------------------------------------

(secretflow) root@DESKTOP-62A5JFJ:~/work/secretflow/secretflow_lib/third_party/heu: cat /root/.cache/bazel/_bazel_root/ea7ef97034bdb43b9ff4f9e4a7919d4e/execroot/com_alipay_sf_heu/bazel-out/k8-fastbuild/testlogs/heu/pybind/phe_test/test.log

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/ea7ef97034bdb43b9ff4f9e4a7919d4e/sandbox/linux-sandbox/3/execroot/com_alipay_sf_heu/bazel-out/k8-fastbuild/bin/heu/pybind/phe_test.runfiles/com_alipay_sf_heu/heu/pybind/phe_test.py", line 17, in <module>
    from heu.pybind import phe
ImportError: /root/.cache/bazel/_bazel_root/ea7ef97034bdb43b9ff4f9e4a7919d4e/sandbox/linux-sandbox/3/execroot/com_alipay_sf_heu/bazel-out/k8-fastbuild/bin/heu/pybind/phe_test.runfiles/com_alipay_sf_heu/heu/pybind/phe.so: undefined symbol: **PyFrame_GetCode**

**Comment by anakinxc** [comment]
Can you try 
`bazel clean --expunge`
and run your commands again?

**Comment by hushanxue** [comment]
> 

It works，thanks a lot. But I don't known why, Could you tell me? Thanks always.

**Comment by anakinxc** [comment]
bazel compilation cache sometimes fails to detect python environment changes, especially when using conda, and eventually build artifacts are built with wrong python.
