### ISSUE TITLE
error installing sf-heu

### ISSUE THREAD

**Issue by randoracle** [secretflow/heu#14]
Hi, thanks for the library!

I encounter this error when installing sf-heu for generating docs.
```
/heu/docs$ pip install sf-heu
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement sf-heu (from versions: none)
ERROR: No matching distribution found for sf-heu
```

Can you have a look? Thank in advance!

**Comment by anakinxc** [comment]
Could you provide your os/python/pip version?

**Comment by randoracle** [comment]
Here is the information:
Pop!_OS 22.04 LTS
Python 3.10.4
pip 22.0.2
