### ISSUE TITLE
问题：ou代码实现与论文差异的疑问

### ISSUE THREAD

**Issue by fsx379** [secretflow/heu#155]
在阅读ou代码与论文时，发现有些差异，故请教下~
（1）密钥生成  ou/he_kit.cc中
gp生成 MPInt::PowMod(g % sk_->p2_, sk_->p_ - MPInt::_1_, sk_->p2_, &gp);
（2）解密 ou/decryptor.cc
MPInt::PowMod(c % sk_->p2_, sk_->t_, sk_->p2_, &c);

论文中 gp = g^p−1 mod p ^ 2 
c = c ^ t mod p ^ 2 

问题：
（g % p2）^p  mod   p ^ 2 和  g^p  mod   p ^ 2 ， （c % p2）^ t  mod   p ^ 2 和c ^ t  mod  p ^ 2是等价的吗？是数学特性吗？

**Comment by zimu-yuxi** [comment]
请问参考的是哪篇论文呢

**Comment by fsx379** [comment]
> 请问参考的是哪篇论文呢

Accelerating Okamoto-Uchiyama’s Public-Key Cryptosystem

**Comment by usafchn** [comment]
原始 paper 就是模 p^2 呀
![image](https://github.com/user-attachments/assets/6449b6ca-7e38-45fe-9f2b-77d53fd81c28)

**Comment by shaojian-ant** [comment]
(base^exponent) % modulus 和 ((base%modulus)^exponent) % modulus 是等价的

**Comment by fsx379** [comment]
> (base^exponent) % modulus 和 ((base%modulus)^exponent) % modulus 是等价的
原来如此，了解了。

ps：模 p^2 那个确实是贴漏，已修改~~~
