### ISSUE TITLE
SEAL 中明文模，多项式系数模数链中单个模最大为 60bits 的解释

### ISSUE THREAD

**Issue by usafchn** [secretflow/heu#48]
转自微信群用户提问，如题

**Comment by xfap** [comment]
**Actually, this is a requirement from Seal's NTT impl.** 

Specifically, see the **checks** before call [`CreateNTTTables`](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/ntt.h#L191) in [`RNSTool::initialize`](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/rns.cpp#L578) and [`SEALContext::validate`](https://github.com/microsoft/SEAL/blob/main/native/src/seal/context.cpp#L135)

Seal's NTT impl is based on double-word integer(uint_64) [see [Class Modulus](https://github.com/microsoft/SEAL/blob/main/native/src/seal/modulus.h#L371) served as [ntt modulus](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/ntt.h#L169)] for efficiency, in which lazy modular reductions in the NTT algorithm would take over 2 bits [see Constraint 1 [P6](https://hal.science/hal-01242273/document)]. As a result, there only rest 62 bits could used for NTT number.  
Not sure for Seal's NTT, but the known shoup's [NTL lib](https://libntl.org/) adapt 60 bits as the largest modulus bits, thinking its more advantageous.
> It is also possible to adapt the logic to work with w = 62, but for a number of reasons, choosing w = 60 is advantageous. 
> see **Sec3.2 P11** https://www.shoup.net/papers/akl-chapter.pdf

And there are other NTL libs adapt just 62-bit mudulus like [HEXL](https://github.com/intel/hexl)(could used in Seal by enabling flag [`SEAL_USE_INTEL_HEXL`](https://github.com/microsoft/SEAL#basic-cmake-options) ) and [NFLlib](https://github.com/quarkslab/NFLlib).

---

**More info, several efficiency benchmark for NTL libs.**

**2016 data** from NFLlib bench [P10](https://hal.science/hal-01242273/document)
<img width="737" alt="image" src="https://user-images.githubusercontent.com/27057528/223307566-1b2a0581-cdc0-421a-8eba-01a8c2c2913e.png">
> Note at that time shoup's [NTL lib](https://libntl.org/) didn't realize float-point free NTT impl. So above 62-bit modulus adapt multi-precision modulus for NTL based on ZZ_pX which has worse performance.

**2021 data** from NTL lib bench [P17](https://www.shoup.net/papers/akl-chapter.pdf)
![Pasted image 20230307105721](https://user-images.githubusercontent.com/27057528/223308724-dcd9a4b2-03b0-491a-8ed9-0e5ac73f7cc4.png)
- floating-point-free implementations work with 60 bits
-  floating-point implementations that do not rely at all on a double-word integer type (and which work with 50-bit primes)

**Comment by lidh15** [comment]
heu.phe里使用seal的文档在哪，没有找到

**Comment by usafchn** [comment]
> heu.phe里使用seal的文档在哪，没有找到

您好，HEU 目前暂时还不支持 FHE，也没法调用 Seal，请谅解。

HEU 是一个纯性能导向的产品，我们正在不断打磨 PHE 的性能，PHE 相对完善后我们会启动 FHE 的开发工作，尽请期待
