### ISSUE TITLE
OU解密

### ISSUE THREAD

**Issue by ssdyue** [secretflow/heu#69]
https://github.com/secretflow/heu/blob/42fc559b83f7f775b8a1072faadefefa0d26c8a6/heu/library/algorithms/ou/decryptor.cc#L32

根据ou解密公式   (c-1)/p * gp_inv mod p，此处是否少减了1:
`MPInt::MulMod((c-MPInt::_1_) / sk_.p_, sk_.gp_inv_, sk_.p_, out); `

**Comment by usafchn** [comment]
@ssdyue 
上一行代码，第31行不就把 c减了1吗
https://github.com/secretflow/heu/blob/42fc559b83f7f775b8a1072faadefefa0d26c8a6/heu/library/algorithms/ou/decryptor.cc#LL31C15-L31C15

**Comment by ssdyue** [comment]
> @ssdyue 上一行代码，第31行不就把 c减了1吗 https://github.com/secretflow/heu/blob/42fc559b83f7f775b8a1072faadefefa0d26c8a6/heu/library/algorithms/ou/decryptor.cc#LL31C15-L31C15

是的是的，没注意，hh
