### ISSUE TITLE
将 HEU 部分中文文档从中文翻译成英文

### ISSUE THREAD

**Issue by Candicepan** [secretflow/heu#72]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：将 HEU 部分中文文档从中文翻译成英文，具体包括：
  1. 《[算法选择](https://www.secretflow.org.cn/docs/heu/latest/en-US/getting_started/algo_choice)》全文
  2. 《[FAQ](https://www.secretflow.org.cn/docs/heu/latest/en-US/getting_started/faq#heu-python)》小部分中文内容
  3. 《[开发新算法](https://www.secretflow.org.cn/docs/heu/latest/en/development/phe_dev)》小部分中文内容
- 技术方向：HEU/docs
- 任务难度：基础

## 详细要求

将上述提到的 HEU 中文文档按下述要求逐句翻译成英文文档

- 操作指引：[操作指引](https://www.yuque.com/secret-flow/admin/uwv3kw683w24czs8#ymZYq)中有 step by step 的操作介绍，可按照文档方式进行实现
- 文档范例：可在[这里](https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/reference/scql_security_statement)查看文档范例
- 提交要求：请在完成整篇文章翻译后，再提交 PR
- 翻译规范：为了让翻译后的文档更具有统一性，在翻译时可以参考[文档翻译规范](https://www.yuque.com/secret-flow/admin/uwv3kw683w24czs8#pV0sp)中的小 tips

## 能力要求
- 了解基本 git 操作
- 外语水平良好

**Comment by zzrs123** [comment]
zzrs123 Give it to me

**Comment by Candicepan** [comment]
> zzrs123 Give it to me

您还没有完成报名哈，记得点击[这里](https://www.wjx.top/vm/tUFjR9r.aspx)完成报名哟
