### ISSUE TITLE
在 HEU 中实现 Damgård–Jurik 加法同态加密算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/heu#76]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 HEU 中实现 Damgård–Jurik 加法同态加密算法
- 技术方向：加法同态加密，密码学，软件工程，数论
- 任务难度：挑战🌟🌟🌟

## 详细要求
请按照[操作指引](https://www.secretflow.org.cn/docs/heu/latest/zh-Hans/development/phe_dev)，在 HEU 中正确实现 Damgård–Jurik 算法，包括实现代码与对应文档：
- 代码要求：
  - 算法支持在 Linux (x86-64) 和 Mac(Intel/m1) 平台上运行
  - 为 Damgård–Jurik 算法添加必要的单元测试
  - HEU 已有单测与新增单测必须跑通
  - 需遵守[编码规范](https://github.com/secretflow/heu/blob/main/CONTRIBUTING.md)
-  增加一个 README 文档，用于描述您实现的 Damgård–Jurik 算法公式，可参考[样例](https://github.com/secretflow/heu/blob/main/heu/library/algorithms/elgamal/README.md)
- 提交要求：关联该 issue 并按照[操作指引](https://www.secretflow.org.cn/docs/heu/latest/zh-Hans/development/phe_dev)将代码以及 README 文档提交至 https://github.com/secretflow/heu

## 能力要求
- 具备初步的密码学，特别是加法同态加密知识
- 具备一点点数学，特别是数论相关的知识
- 精通 C++

## 操作说明
- 操作指引：可参考文档[如何在 HEU 中添加新算法](https://www.secretflow.org.cn/docs/heu/latest/zh-Hans/development/phe_dev)
  - 说明：上述文档中接口分为 Scalar 和 Vectorized 两个版本，本次任务，仅需实现 Scalar 版本即可
- 操作指南：在提交 PR 时，请先 fork HEU 仓库，将新增代码放入 fork 仓库，然后在 fork 仓库中发起 Pull Request 并将代码 merge 至 HEU 仓库的 main 分支

**Comment by zhangwfjh** [comment]
zhangwfjh Give it to me
