### ISSUE TITLE
HEU是否支持GPU计算？

### ISSUE THREAD

**Issue by dtera** [secretflow/heu#88]
HEU是否支持GPU计算？如果不支持，是否有这方面的计划

**Comment by usafchn** [comment]
基于硬件加速的算法以合作团队、社区贡献为主，曾经有一个团队给 HEU 贡献了 GPU Paillier 算法，但是性能一直没有达到预期，因此没有放到 github 上。合作团队的人力不太可控，短期内调优 GPU Paillier 的性能希望渺茫，而我们内部暂时没有往 GPU 方向投入资源的计划
