### ISSUE TITLE
heu是否需要对不同语言调用的支持

### ISSUE THREAD

**Issue by dtera** [secretflow/heu#90]
目前我们团队在spark分布式环境中使用了heu，封装了heu的API并提供了JNI接口，如果需要可以commit到该项目中，后续可能还会有其他语言会使用heu

**Comment by usafchn** [comment]
嗯嗯可以的，感谢

**Comment by tarantula-leo** [comment]
> 目前我们团队在spark分布式环境中使用了heu，封装了heu的API并提供了JNI接口，如果需要可以commit到该项目中，后续可能还会有其他语言会使用heu

你好 想问下这部分工作现在有commit到heu项目里吗？

**Comment by tarantula-leo** [comment]
是的，社区会有后续计划么？

**Comment by usafchn** [comment]
> 是的，社区会有后续计划么？

目前没有计划哈，需求我已经记录了
